import Head from 'next/head'
import Link from 'next/link'

export default function PageLayout({
  children,
  title = 'News App',
}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Link href='/'> Home</Link>
        <h2>🗞️ NewsApi</h2>
        <Link href='/about'> About</Link>
      </header>
      <main>{children}</main>
    </>
  )
}
